# Generated by Django 3.0.6 on 2021-03-11 23:11

import apps.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_operador_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, validators=[apps.utils.validators.validate_cpf], verbose_name='CPF do usuário'),
        ),
    ]
