# Generated by Django 3.2.3 on 2021-12-02 13:33
from django.db import migrations
from django.db import models

import apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [("users", "0005_auto_20210405_1556")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[apps.utils.validators.validate_cpf],
                verbose_name="CPF do usuário",
            ),
        )
    ]
