# Generated by Django 3.0.6 on 2020-12-04 01:15

import apps.gestao.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_proposta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='arquivo_nf',
            field=models.FileField(blank=True, null=True, upload_to=apps.gestao.upload.UploadToPath('nf'), verbose_name='Dut ou NF'),
        ),
    ]
