# Generated by Django 3.0.6 on 2020-12-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_proposta_arquivo_nf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='codigo',
        ),
        migrations.AddField(
            model_name='proposta',
            name='origem',
            field=models.CharField(blank=True, max_length=255, verbose_name='Origem/Lead'),
        ),
    ]
