# Generated by Django 3.1.7 on 2021-04-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_auto_20201203_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='comissao_campanha',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='proposta',
            name='valor_comissao_campanha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='n_contrato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='veiculo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
