# Generated by Django 3.0.6 on 2020-06-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_em', models.DateTimeField(auto_now=True)),
                ('session_hash', models.CharField(max_length=40, unique=True, verbose_name='Código Interno')),
                ('stage', models.CharField(default='1', max_length=10, verbose_name='Estágio')),
                ('valor_do_veiculo', models.CharField(blank=True, max_length=20, verbose_name='Valor do Veículo')),
                ('valor_de_entrada', models.CharField(blank=True, max_length=20, verbose_name='Valor de Entrada')),
                ('cpf', models.CharField(blank=True, max_length=20, verbose_name='CPF')),
                ('prazo', models.CharField(blank=True, choices=[('12x', '12x'), ('24x', '24x'), ('36x', '36x'), ('48x', '48x'), ('60x', '60x')], max_length=3, verbose_name='Prazo')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('data_de_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=100, verbose_name='Sexo')),
                ('numero_do_rg', models.CharField(blank=True, max_length=100, verbose_name='Número do RG')),
                ('orgao_expedidor', models.CharField(blank=True, max_length=100, verbose_name='Órgão Expedidor')),
                ('nome_da_mae', models.CharField(blank=True, max_length=100, verbose_name='Nome da Mãe')),
                ('local_de_nascimento', models.CharField(blank=True, max_length=100, verbose_name='Local de Nascimento')),
                ('uf_de_nascimento', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF de Nascimento')),
                ('cep', models.CharField(blank=True, max_length=100, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=100, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=100, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF')),
                ('telefone_fixo', models.CharField(blank=True, max_length=100, verbose_name='Telefone Fixo')),
                ('celular', models.CharField(blank=True, max_length=100, verbose_name='Celular')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('tipo_de_renda', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Renda')),
                ('renda_mensal_pessoal', models.CharField(blank=True, max_length=100, verbose_name='Renda Mensal Pessoal')),
                ('profissao', models.CharField(blank=True, max_length=100, verbose_name='Profissão')),
                ('cep_da_empresa', models.CharField(blank=True, max_length=100, verbose_name='CEP da Empresa')),
                ('endereco_comercial', models.CharField(blank=True, max_length=100, verbose_name='Endereço Comercial')),
                ('numero_empresa', models.CharField(blank=True, max_length=100, verbose_name='Número')),
                ('complemento_empresa', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade_empresa', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('uf_empresa', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF')),
                ('inicio_da_atividade', models.CharField(blank=True, max_length=100, verbose_name='Início da Atividade')),
                ('telefone_fixo_da_empresa', models.CharField(blank=True, max_length=100, verbose_name='Telefone Fixo da Empresa')),
                ('tempo_de_empresa', models.CharField(blank=True, max_length=100, verbose_name='Tempo de Empresa (anos)')),
                ('razao_social_da_empresa', models.CharField(blank=True, max_length=100, verbose_name='Razão Social da Empresa')),
                ('cnpj_da_empresa', models.CharField(blank=True, max_length=100, verbose_name='CNPJ da empresa')),
                ('tempo_de_atividade', models.CharField(blank=True, max_length=100, verbose_name='Tempo de Atividade')),
                ('tempo_de_aposentadoria', models.CharField(blank=True, max_length=100, verbose_name='Tempo de Aposentadoria')),
                ('outras_rendas', models.CharField(blank=True, max_length=100, verbose_name='Outras Rendas')),
                ('ano_de_fabricacao', models.CharField(blank=True, max_length=100, verbose_name='Ano de Fabricação')),
                ('ano_do_modelo', models.CharField(blank=True, max_length=100, verbose_name='Ano do Modelo')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('versao', models.CharField(blank=True, max_length=100, verbose_name='Versão')),
                ('combustivel', models.CharField(blank=True, max_length=100, verbose_name='Combustível')),
                ('cambio', models.CharField(blank=True, max_length=100, verbose_name='Câmbio')),
                ('motor', models.CharField(blank=True, max_length=100, verbose_name='Motor')),
                ('placa', models.CharField(blank=True, max_length=100, verbose_name='Placa')),
                ('renavam', models.CharField(blank=True, max_length=100, verbose_name='Renavam')),
                ('chassi', models.CharField(blank=True, max_length=100, verbose_name='Chassi')),
            ],
        ),
    ]
