# Generated by Django 3.0.6 on 2020-08-29 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalGiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=300, verbose_name='Telefone')),
                ('prazo', models.PositiveSmallIntegerField(help_text='1x a 24x', validators=[django.core.validators.MaxValueValidator(24)], verbose_name='Prazo')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('faturamento_anual', models.CharField(choices=[('200-500', '200 mil - 500 mil'), ('500-1', '500 mil - 1 milhão'), ('1-2', '1 milhão - 2 milhões'), ('2-5', '2 milhões - 5 milhões'), ('5-10', '5 milhões - 10 milhões'), ('10-20', '10 milhões - 20 milhões'), ('20-30', '20 milhões - 30 milhões'), ('30-50', '30 milhões - 50 milhões'), ('50-', 'acima de 50 milhões')], max_length=100, verbose_name='Faturamento anual da empresa')),
                ('valor_emprestimo', models.CharField(help_text='Máximo de 800 mil', max_length=100, verbose_name='Valor do emprestimo')),
            ],
            options={
                'verbose_name': 'Capital de Giro',
                'verbose_name_plural': 'Capitais de Giro',
            },
        ),
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=100, verbose_name='CPF')),
                ('pessoa', models.CharField(choices=[('fisica', 'Pessoa Física'), ('juridica', 'Pessoa Jurídica')], max_length=100, verbose_name='Pessoa')),
                ('bandeira', models.CharField(choices=[('visa', 'Visa'), ('master', 'Master')], max_length=100, verbose_name='Bandeira')),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=100, verbose_name='Sexo')),
                ('data_de_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('nome_mae', models.CharField(max_length=254, verbose_name='Nome da mãe')),
                ('endereco', models.CharField(max_length=254, verbose_name='Endereço Residencial')),
                ('cep', models.CharField(max_length=12, verbose_name='CEP')),
                ('vencimento', models.CharField(choices=[('1', '1'), ('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30')], max_length=2, verbose_name='Dia do Vencimento')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
            },
        ),
        migrations.CreateModel(
            name='FinanciamentoVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_do_veiculo', models.CharField(max_length=100, verbose_name='Valor do Veículo')),
                ('entrada', models.CharField(max_length=100, verbose_name='Valor de Entrada')),
                ('cpf', models.CharField(max_length=100, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Financiamento de Veículo',
                'verbose_name_plural': 'Financiamentos de Veículos',
            },
        ),
    ]
