# Generated by Django 3.0.6 on 2021-02-16 20:07
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("delta", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="capitalgiro",
            name="criado_em",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="capitalgiro",
            name="modificado_em",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="cartaocredito",
            name="criado_em",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="cartaocredito",
            name="modificado_em",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="financiamentoveiculo",
            name="ano",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="financiamentoveiculo",
            name="criado_em",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="financiamentoveiculo",
            name="email",
            field=models.EmailField(default="", max_length=254, verbose_name="E-mail"),
        ),
        migrations.AddField(
            model_name="financiamentoveiculo",
            name="modificado_em",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="financiamentoveiculo",
            name="tipo_veiculo",
            field=models.CharField(
                choices=[
                    ("carro", "Carro"),
                    ("moto", "Moto"),
                    ("utilitario", "Utilitário"),
                    ("caminhao", "Caminhão"),
                ],
                default="carro",
                max_length=100,
            ),
        ),
    ]
