# Generated by Django 3.0.6 on 2020-06-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='bairro_empresa',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
    ]
