# Generated by Django 3.0.6 on 2020-07-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0003_auto_20200710_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposta',
            old_name='profissao',
            new_name='profissao_assalariado',
        ),
        migrations.AddField(
            model_name='proposta',
            name='profissao_liberal',
            field=models.CharField(blank=True, choices=[('ADVOGADOS', 'ADVOGADOS'), ('ARQUITETOS', 'ARQUITETOS'), ('ENGENHEIROS', 'ENGENHEIROS'), ('MÉDICOS E CIRURGIÕES DENTISTAS', 'MÉDICOS E CIRURGIÕES DENTISTAS'), ('PROFESSORES', 'PROFESSORES'), ('OUTROS', 'OUTROS')], max_length=100, verbose_name='Profissão'),
        ),
    ]
