# Generated by Django 3.0.6 on 2021-03-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0004_auto_20210223_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiamentoveiculo',
            name='ano',
            field=models.PositiveSmallIntegerField(default=2010),
        ),
    ]
