# Generated by Django 3.0.6 on 2020-07-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0004_auto_20200711_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='dados_placa',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=100, verbose_name='VOCÊ POSSUI OS DADOS DE PLACA / CHASSI / RENAVAM DESTE VEÍCULO?'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='ano_de_fabricacao',
            field=models.CharField(blank=True, help_text='Veículo', max_length=100, verbose_name='Ano de Fabricação'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='tipo_de_renda',
            field=models.CharField(blank=True, choices=[('assalariado', 'assalariado'), ('autonomo', 'autonomo'), ('empresario', 'empresario'), ('aposentado', 'aposentado')], help_text='<h2>Informe a renda do seu cliente</h2><h3>Essas informações são essenciais para análise de crédito do financiamento</h3>', max_length=100, verbose_name='Tipo de Renda'),
        ),
    ]
