# Generated by Django 3.2.3 on 2021-11-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0005_auto_20210308_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiamentoveiculo',
            name='ano',
            field=models.PositiveSmallIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='financiamentoveiculo',
            name='tipo_veiculo',
            field=models.CharField(choices=[('  ', '  '), ('carro', 'Carro'), ('moto', 'Moto'), ('utilitario', 'Utilitário'), ('caminhao', 'Caminhão')], default='carro', max_length=100),
        ),
    ]
