# Generated by Django 3.2.3 on 2021-12-02 13:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("delta", "0005_auto_20210308_1612")]

    operations = [
        migrations.AlterField(
            model_name="financiamentoveiculo",
            name="ano",
            field=models.PositiveSmallIntegerField(default=""),
        )
    ]
