# Generated by Django 3.0.6 on 2020-11-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propostaporto',
            name='stage',
        ),
        migrations.AddField(
            model_name='propostaporto',
            name='pagina',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Página'),
        ),
    ]
