# Generated by Django 3.0.6 on 2021-01-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0002_auto_20201107_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaporto',
            name='estado_simulacao',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Inicial'), (2, 'Erro'), (3, 'Recusado'), (4, 'Aprovado'), (5, 'Credito Pre Aprovado')], default=1, verbose_name='Simulacao'),
        ),
    ]
