# Generated by Django 3.0.6 on 2021-02-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0003_propostaporto_estado_simulacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaporto',
            name='mensagem',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
