# Generated by Django 3.1.7 on 2021-04-14 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0005_propostaporto_valor_financiado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostaporto',
            name='ano_de_fabricacao',
            field=models.CharField(blank=True, help_text='<h2>Informações sobre o Veículo</h2><p>Caso seu cliente não saiba exatamente qual veículo irá comprar, indique algum compatível em termos de preço. Fique tranquilo, você poderá mudar essa informação a qualquer momento.</p>', max_length=100, verbose_name='Ano de Fabricação'),
        ),
        migrations.AlterField(
            model_name='propostaporto',
            name='chassi',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17)], verbose_name='Chassi'),
        ),
        migrations.AlterField(
            model_name='propostaporto',
            name='combustivel',
            field=models.CharField(blank=True, choices=[('Gasolina/Alcool/Flex', 'Gasolina/Alcool/Flex'), ('Hibrido', 'Hibrido'), ('Eletrico', 'Elétrico')], max_length=100, verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='propostaporto',
            name='placa',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)], verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='propostaporto',
            name='prazo',
            field=models.CharField(choices=[('12', '12x'), ('24', '24x'), ('36', '36x'), ('48', '48x'), ('60', '60x')], help_text='<h2>Prazo de Financiamento</h2><h3>Selecione a melhor opção para seu cliente.</h3>', max_length=3, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='propostaporto',
            name='renavam',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(11)], verbose_name='Renavam'),
        ),
        migrations.AlterField(
            model_name='propostaporto',
            name='tipo_de_renda',
            field=models.CharField(blank=True, choices=[('assalariado', 'assalariado'), ('autonomo', 'autônomo'), ('empresario', 'empresário'), ('aposentado', 'aposentado')], help_text='<h2>Informe a renda do seu cliente</h2><h3>Essas informações são essenciais para análise de crédito do financiamento</h3>', max_length=100),
        ),
    ]
