# Generated by Django 3.2.3 on 2021-06-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0007_auto_20210602_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostaporto',
            name='pagina',
            field=models.CharField(default='', max_length=100, verbose_name='Página'),
        ),
        migrations.AlterField(
            model_name='propostaporto',
            name='pessoa',
            field=models.CharField(choices=[('', ''), ('pf', 'pf'), ('pj', 'pj')], default='pf', max_length=100),
        ),
    ]
