# Generated by Django 3.2.3 on 2021-12-02 13:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("porto", "0008_auto_20210609_1144")]

    operations = [
        migrations.AlterField(
            model_name="propostaporto",
            name="combustivel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Gasolina/Alcool/Flex", "Gasolina/Alcool/Flex"),
                    ("Diesel", "Diesel"),
                    ("Hibrido", "Hibrido"),
                    ("Eletrico", "Elétrico"),
                ],
                max_length=100,
                verbose_name="Combustível",
            ),
        ),
        migrations.AlterField(
            model_name="propostaporto",
            name="uf",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "AC"),
                    ("AL", "AL"),
                    ("AP", "AP"),
                    ("AM", "AM"),
                    ("BA", "BA"),
                    ("CE", "CE"),
                    ("DF", "DF"),
                    ("ES", "ES"),
                    ("GO", "GO"),
                    ("MA", "MA"),
                    ("MT", "MT"),
                    ("MS", "MS"),
                    ("MG", "MG"),
                    ("PA", "PA"),
                    ("PB", "PB"),
                    ("PR", "PR"),
                    ("PE", "PE"),
                    ("PI", "PI"),
                    ("RJ", "RJ"),
                    ("RN", "RN"),
                    ("RS", "RS"),
                    ("RO", "RO"),
                    ("RR", "RR"),
                    ("SC", "SC"),
                    ("SP", "SP"),
                    ("SE", "SE"),
                    ("TO", "TO"),
                ],
                max_length=2,
                verbose_name="UF",
            ),
        ),
    ]
