# Generated by Django 3.2.3 on 2021-11-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0008_auto_20210609_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostaporto',
            name='cambio',
            field=models.CharField(blank=True, choices=[('  ', '  '), ('Manual', 'Manual'), ('Automatico', 'Automático')], max_length=100, verbose_name='Câmbio'),
        ),
        migrations.AlterField(
            model_name='propostaporto',
            name='combustivel',
            field=models.CharField(blank=True, choices=[('  ', '  '), ('Gasolina/Alcool/Flex', 'Gasolina/Alcool/Flex'), ('Diesel', 'Diesel'), ('Hibrido', 'Hibrido'), ('Eletrico', 'Elétrico')], max_length=100, verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='propostaporto',
            name='profissao_assalariado',
            field=models.CharField(blank=True, choices=[('  ', '  '), ('ADMINISTRADORES / ECONOMISTAS', 'ADMINISTRADORES / ECONOMISTAS'), ('ANALISTAS', 'ANALISTAS'), ('CONSULTOR', 'CONSULTOR'), ('DIRETOR DE EMPRESA', 'DIRETOR DE EMPRESA'), ('FUNCIONÁRIO DE EMPRESAS PUBLICAS', 'FUNCIONÁRIO DE EMPRESAS PUBLICAS'), ('GERENTE', 'GERENTE'), ('OPERADOR EM GERAL', 'OPERADOR EM GERAL'), ('OUTRAS PROFISSÕES DA INDUSTRIA', 'OUTRAS PROFISSÕES DA INDUSTRIA'), ('OUTRAS PROFISSÕES NO COMÉRCIO', 'OUTRAS PROFISSÕES NO COMÉRCIO'), ('PROFESSORES', 'PROFESSORES'), ('PROMOTOR', 'PROMOTOR'), ('VENDEDORES / REPRESENTANTES / INTERMEDIÁRIOS', 'VENDEDORES / REPRESENTANTES / INTERMEDIÁRIOS'), ('OUTROS', 'OUTROS')], max_length=100, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='propostaporto',
            name='uf_de_nascimento',
            field=models.CharField(blank=True, choices=[('  ', '  '), ('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF de Nascimento'),
        ),
        migrations.AlterField(
            model_name='propostaporto',
            name='uf_empresa',
            field=models.CharField(blank=True, choices=[('  ', '  '), ('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF'),
        ),
    ]
